name: Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1.1.0
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Obtain CRX packager
      run: npm install crx
