name: Create ZIP

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Publish package.zip to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Extension ZIP
        path: ./
