name: Create ZIP

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Create package.zip
    - uses: TheDoctor0/zip-release@v0.2.1
      with:
        filename: 'package.zip'
        exclusions: '*.git* README.md'
    - name: Publish package.zip to artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.os }}
        path: package.zip
